name: chicago_crime
version: 1.0.0
config-version: 2

profile: chicago_crime

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  chicago_crime:
    +materialized: view

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
